apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlos-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: testing
  template:
    metadata:
      name: htmlos-pod
      labels:
        env: testing
    spec:
      containers:
      - name: htmlos-con
        image: krushnakant241/mywebos:v1
        ports:
        - containerPort: 80
          NodePort: 31000
        volumeMounts:
        - name: phpos-persistent-storage
          mountPath: /var/www/html
      volumes: 
      - name: htmlos-persistent-storage
        persistentVolumeClaim:
            claimName: htmlos-pvc-claim
