apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpos-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: testing
  template:
    metadata:
      name: phpos-pod
      labels:
        env: testing
    spec:
      containers:
      - name: phpos-con
        image: vimal13/apache-webserver-php:latest
        ports:
        - containerPort: 80
          NodePort: 30000
        volumeMounts:
        - name: phpos-persistent-storage
          mountPath: /var/www/html
      volumes: 
      - name: phpos-persistent-storage
        persistentVolumeClaim:
            claimName: phpos-pvc-claim
