apiVersion: v1
kind: Service
metadata:
  name: phpos-service
spec:
  type: NodePort
  selector:
    app: php-service-node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpos-pvc-claim
  labels: 
    name: phpospvcclaim
spec: 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpos-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: testing
  template:
    metadata:
      name: phpos-pod
      labels:
        env: testing
    spec:
      containers:
      - name: phpos-con
        image: vimal13/apache-webserver-php:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: phpos-persistent-storage
          mountPath: /var/www/html
      volumes: 
      - name: phpos-persistent-storage
        persistentVolumeClaim:
            claimName: phpos-pvc-claim
